services:
  blog:
    image: ghcr.io/dethanev/blog:latest
    container_name: blog
    restart: always
    pull_policy: always
    ports:
      - "8080:80"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      DOCKER_API_VERSION: "1.45"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup
